#!/usr/bin/env bash

LATEST_VERSION="v5.12_stable"

if [ "$DOCKER_TAG" = "latest" ]; then
  PAPARAZZI_TAG=$LATEST_VERSION
else
  PAPARAZZI_TAG=$DOCKER_TAG
fi

docker build -t ${IMAGE_NAME} \
  --build-arg paparazzi_tag=$PAPARAZZI_TAG \
  .
